version: 2

CI_IMAGE: &CI_IMAGE circleci/node:lts

jobs:
  install-dependencies:
    docker:
      - image: *CI_IMAGE
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          key: node-modules-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: *CI_IMAGE
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    docker:
      - image: *CI_IMAGE
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn test

workflows:
  version: 2
  pipeline:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
